[tasks.init-deps]
script='''
#!/usr/bin/env bash
rustup toolchain install nightly
rustup default nightly
rustup target add wasm32-unknown-unknown
'''

[tasks.dev]
script = '''
#!/usr/bin/env bash
cargo leptos watch
'''

[tasks.pre-production]
script = '''
#!/usr/bin/env bash
USER_SHELL="${SHELL}"

# minify main css, leptos does not do this, lightningcss also removes imports and inlines content
"${USER_SHELL}" -c "lightningcss --minify --bundle --targets '>= 0.25%' ./target/site/pkg/this-app.css -o ./target/site/pkg/this-app.css"
# compress all
"${USER_SHELL}" -c "precompress ./target/site --brotli --zstd"
# then create a container image
'''